name: Flatpak Builder

on:
  release:
    types: [published]
  workflow_dispatch: 

jobs:
  # from https://github.com/flatpak/flatpak-github-actions
  flatpak:
    name: "Flatpak"
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:kde-6.9
      options: --privileged
    strategy:
      matrix:
        variant:
          - arch: x86_64
            runner: ubuntu-24.04
          - arch: aarch64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.variant.runner }}
    steps:
      - uses: actions/checkout@v6
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: eu.opencloud.Desktop.flatpak
          manifest-path: flatpak/eu.opencloud.Desktop.yml
          cache-key: flatpak-builder-${{ github.sha }}
          arch: ${{ matrix.variant.arch }}
          verbose: true
      - uses: flatpak/flatpak-github-actions/flat-manager@v6
        name: "Deploy"
        with:
          repository: opencloud # The repository to push the build into
          flat-manager-url: https://flatpak-api.elementary.io # The flat-manager remote URL
          token: some_very_hidden_token # A flat-manager token